### ISSUE TITLE
Copy AMI image ami-af7359c5 to us-east-2 region

### ISSUE THREAD

**Issue by zhangwenjia0326** [ConcurrenyLabs/jmeter-cw-logs#2]
Hi, 

Could someone from your team please copy this AMI to us-east-2. We want to use your template in Ohio region, but don't have the permission to copy it to us-east-2. Getting the error message: "You do not have permission to access the storage of this ami". 

Thanks, 
Wen

**Comment by concurrencylabs** [comment]
We've just created public AMI ami-0c0df429dcca168b6 in Ohio. This should solve the issue.

**Comment by zhangwenjia0326** [comment]
Thank you so much for looking into this for me!!
